//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnoses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnoses()
        {
            this.HistoryOfDisease = new HashSet<HistoryOfDisease>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Simptoms { get; set; }
        public string TimeOfHeal { get; set; }
        public string Appointments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryOfDisease> HistoryOfDisease { get; set; }
    }
}
