//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors()
        {
            this.HistoryOfDisease = new HashSet<HistoryOfDisease>();
        }
    
        public int id { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Patronymic { get; set; }
        public string Post { get; set; }
        public int WorkExp { get; set; }
        public string SienceRank { get; set; }
        public string Address { get; set; }
        public int Otdel_id { get; set; }
    
        public virtual Otdel Otdel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryOfDisease> HistoryOfDisease { get; set; }
        public string FullName
        {
            get
            {
                string go = string.Empty;
                go = Surname + " " + Firstname + " " + Patronymic;
                return go;
            }
        }
    }
}
