//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOfDisease
    {
        public int id { get; set; }
        public int Patient_Id { get; set; }
        public int Doctor_Id { get; set; }
        public int Diagnoses_Id { get; set; }
        public string Heal { get; set; }
        public System.DateTime DateOfDisease { get; set; }
        public Nullable<System.DateTime> DateOfCloseDisease { get; set; }
        public string TypeOfHeal { get; set; }
    
        public virtual Diagnoses Diagnoses { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
        public string Close
        {
            get
            {
                string go = string.Empty;
                if(string.IsNullOrWhiteSpace(DateOfCloseDisease.ToString()))
                {
                    go = "Больничный лист ещё не закрыт";
                } else
                {
                    go = DateOfCloseDisease.ToString();
                }
                return go;
            }
        }
    }
}
